name: Build DrelbsOS Kernel

on:
  schedule:
    - cron: '05 10 * * 2'  # 10:05am UTC tue
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  IMAGE_BASE_NAME: drelbsos-kernel
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  BUILDER_IMAGE: fedora_builder

jobs:
  build_kernel:
    environment: prod
    strategy:
      fail-fast: false
      matrix:
        arch: ["x86_64"]
        fedora_version: [42]
    runs-on: ${{ 'ubuntu-24.04' }}

    steps:
      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v9

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore ccache
        # Don't use cache on releases as github does not allow it
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/cache/restore@v4
        with:
          path: ccache
          key: ccache-${{ matrix.arch }}-${{ github.sha }}
          restore-keys: |
            ccache-${{ matrix.arch }}

      - name: Determine latest Fedora kernel version
        id: kernel-version
        run: |
          git clone https://src.fedoraproject.org/rpms/kernel.git -b f"${{ matrix.fedora_version }}" --depth 1 kver
          cd kver
          # Get the kernel version from the spec file
          SPEC_RPM_VERSION=$(grep "^%define specrpmversion" kernel.spec | awk '{print $3}')
          PKG_RELEASE=$(grep "^%define pkgrelease" kernel.spec | awk '{print $3}')
          # Output the version in the standard format
          KERNEL_VER="${SPEC_RPM_VERSION}-${PKG_RELEASE}.fc${{ matrix.fedora_version }}"
          echo "Found kernel version $KERNEL_VER"
          cd ../
          rm -rf kver
          echo "version=$KERNEL_VER" >> $GITHUB_OUTPUT

      - name: Build kernel and modules
        run: |
          mkdir -p $(pwd)/ccache
          FEDORA_MAJOR_VERSION="${{ matrix.fedora_version }}"
          sudo podman build -f Containerfile . --tag '${{ env.BUILDER_IMAGE }}:${{ steps.kernel-version.outputs.version }}' \
            --build-arg FEDORA_MAJOR_VERSION=${{ matrix.fedora_version }} \
            --env CCACHE_DIR=/workspace/ccache \
            --env CCACHE_MAXSIZE=5G \
            --env CCACHE_COMPRESS=1 \
            -v $(pwd)/ccache:/workspace/ccache

      - name: Print ccache stats
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          sudo apt install -y ccache
          ccache -s

      - name: Push To GHCR
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        run: |
          sudo podman push ${{ env.BUILDER_IMAGE }}:${{ steps.kernel-version.outputs.version }} docker://${{ env.IMAGE_REGISTRY }}/drelbsos-kernel:${{ matrix.fedora_version }} --creds "${{ env.REGISTRY_USER }}:${{ env.REGISTRY_PASSWORD }}"
          sudo podman push ${{ env.BUILDER_IMAGE }}:${{ steps.kernel-version.outputs.version }} docker://${{ env.IMAGE_REGISTRY }}/drelbsos-kernel:${{ steps.kernel-version.outputs.version }} --creds "${{ env.REGISTRY_USER }}:${{ env.REGISTRY_PASSWORD }}"

      # We always want to save the newest ccache
      - name: Backup ccache
        # Don't use cache on releases as github does not allow it
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/cache/save@v4
        with:
          path: ccache
          key: ccache-${{ matrix.arch }}-${{ github.sha }}
