name: Build DrelbsOS Kernel

on:
  workflow_dispatch:
  release:
    types: [published]

permissions: write-all

env:
  IMAGE_BASE_NAME: drelbsos-kernel
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  BUILDER_IMAGE: fedora_builder

jobs:
  build_kernel:
    environment: prod
    strategy:
      fail-fast: false
      matrix:
        arch: ["x86_64"]
        fedora_version: [42]
    runs-on: ${{ 'ubuntu-24.04' }}

    steps:
      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v9

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore ccache
        # Don't use cache on releases as github does not allow it
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/cache/restore@v4
        with:
          path: ccache
          key: ccache-${{ matrix.arch }}-${{ github.sha }}
          restore-keys: |
            ccache-${{ matrix.arch }}

      - name: Create Build Environment
        run: |
          FEDORA_MAJOR_VERSION="${{ matrix.fedora_version }}"
          sudo podman build -f Containerfile.builder . --tag '${{ env.BUILDER_IMAGE }}' \
            --build-arg UID=$(id -u) --build-arg GID=$(id -g) \
            --build-arg FEDORA_MAJOR_VERSION=${{ matrix.fedora_version }}
      - name: Checkout Kernel
        run: |
          FEDORA_MAJOR_VERSION="${{ matrix.fedora_version }}"
          ARCH="${{ matrix.arch }}"
          DISABLE_ARG="${{ startsWith(github.ref, 'refs/tags/') && '--env CCACHE_DISABLE=true' || '' }}"
          sudo podman run --rm -v $(pwd):/workspace \
            ${{ env.BUILDER_IMAGE }} fedpkg \
            co -a kernel -b "f${{ matrix.fedora_version }}"
      - name: LS
        run: |
          FEDORA_MAJOR_VERSION="${{ matrix.fedora_version }}"
          ARCH="${{ matrix.arch }}"
          DISABLE_ARG="${{ startsWith(github.ref, 'refs/tags/') && '--env CCACHE_DISABLE=true' || '' }}"
          sudo podman run --rm -v $(pwd):/workspace \
            ${{ env.BUILDER_IMAGE }} ls -lah kernel
      - name: Update BuildID
        run: |
          FEDORA_MAJOR_VERSION="${{ matrix.fedora_version }}"
          ARCH="${{ matrix.arch }}"
          DISABLE_ARG="${{ startsWith(github.ref, 'refs/tags/') && '--env CCACHE_DISABLE=true' || '' }}"
          sudo podman run --rm -v $(pwd):/workspace -w /workspace/kernel\
            ${{ env.BUILDER_IMAGE }} sed -i 's/^# define buildid \.local$/%define buildid .drelbsos/' kernel.spec
      - name: Update KConfig
        run: |
          FEDORA_MAJOR_VERSION="${{ matrix.fedora_version }}"
          ARCH="${{ matrix.arch }}"
          DISABLE_ARG="${{ startsWith(github.ref, 'refs/tags/') && '--env CCACHE_DISABLE=true' || '' }}"
          sudo podman run --rm -v $(pwd):/workspace -w /workspace/kernel \
            ${{ env.BUILDER_IMAGE }} cat ../drelbsos-kconfig-overrides >> kernel-local
      - name: Remove useless KConfigs
        run: |
          FEDORA_MAJOR_VERSION="${{ matrix.fedora_version }}"
          ARCH="${{ matrix.arch }}"
          DISABLE_ARG="${{ startsWith(github.ref, 'refs/tags/') && '--env CCACHE_DISABLE=true' || '' }}"
          sudo podman run --rm -v $(pwd):/workspace  -w /workspace/kernel \
            ${{ env.BUILDER_IMAGE }} find . -type f -name "kernel*.config" -not -name "kernel-x86_64*.config" -exec rm {} \;
      - name: Remove useless KConfig refs
        run: |
          FEDORA_MAJOR_VERSION="${{ matrix.fedora_version }}"
          ARCH="${{ matrix.arch }}"
          DISABLE_ARG="${{ startsWith(github.ref, 'refs/tags/') && '--env CCACHE_DISABLE=true' || '' }}"
          sudo podman run --rm -v $(pwd):/workspace -w /workspace/kernel \
            ${{ env.BUILDER_IMAGE }} sed -i -E '/(aarch64|riscv64|s390|ppc64le).*\.config/d' kernel.spec
      # - name: Compile Kernel
      #   run: |
      #     FEDORA_MAJOR_VERSION="${{ matrix.fedora_version }}"
      #     ARCH="${{ matrix.arch }}"
      #     DISABLE_ARG="${{ startsWith(github.ref, 'refs/tags/') && '--env CCACHE_DISABLE=true' || '' }}"
      #     sudo podman run --rm -v $(pwd):/workspace $DISABLE_ARG \
      #       --env CCACHE_DIR=/workspace/ccache \
      #       --env CCACHE_MAXSIZE=5G \
      #       --env CCACHE_COMPRESS=1 \
      #       -w /workspace/kernel \
      #       ${{ env.BUILDER_IMAGE }} -- fedpkg \
      #       --name kernel --namespace rpms --release "f${{ matrix.fedora_version }}" \
      #       local --arch ${{ matrix.arch }} --with baseonly \
      #       --builddir build --buildrootdir buildroot
      
      - name: Print ccache stats
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          sudo apt install -y ccache
          ccache -s

      - name: Generate tags
        id: generate-tags
        shell: bash
        run: |
          # Generate a timestamp for creating an image version history
          TIMESTAMP="$(date +%Y%m%d)"
          VARIANT="${{ matrix.fedora_version }}"

          COMMIT_TAGS=()
          BUILD_TAGS=()

          # Have tags for tracking builds during pull request
          SHA_SHORT="${GITHUB_SHA::7}"
          COMMIT_TAGS+=("pr-${{ github.event.number }}-${VARIANT}")
          COMMIT_TAGS+=("${SHA_SHORT}-${VARIANT}")

          BUILD_TAGS=("${VARIANT}" "${VARIANT}-${TIMESTAMP}")

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              echo "Generated the following commit tags: "
              for TAG in "${COMMIT_TAGS[@]}"; do
                  echo "${TAG}"
              done
              default_tag=${COMMIT_TAGS[0]}
              alias_tags=("${COMMIT_TAGS[@]}")
          else
              default_tag=${BUILD_TAGS[0]}
              alias_tags=("${BUILD_TAGS[@]}")
          fi

          echo "Generated the following build tags: "
          for TAG in "${BUILD_TAGS[@]}"; do
              echo "${TAG}"
          done

          echo "alias_tags=${alias_tags[*]}" >> $GITHUB_OUTPUT
          echo "default_tag=$default_tag" >> $GITHUB_ENV

      - name: Push To GHCR
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        run: |
          FEDORA_MAJOR_VERSION="${{ matrix.fedora_version }}"
          ARCH="${{ matrix.arch }}"
          DISABLE_ARG="${{ startsWith(github.ref, 'refs/tags/') && '--env CCACHE_DISABLE=true' || '' }}"

          sudo podman push ${{ env.BUILDER_IMAGE }} docker://${{ env.IMAGE_REGISTRY }}/drelbsos-kernel:${{ matrix.fedora_version }} --creds "${{ env.REGISTRY_USER }}:${{ env.REGISTRY_PASSWORD }}"

      # - name: Push To GHCR
      #   uses: Wandalen/wretry.action@e68c23e6309f2871ca8ae4763e7629b9c258e1ea # v3.8.0
      #   id: push
      #   if: github.event_name != 'pull_request'
      #   env:
      #     REGISTRY_USER: ${{ github.actor }}
      #     REGISTRY_PASSWORD: ${{ github.token }}
      #   with:
      #     action: redhat-actions/push-to-registry@v2 # v2
      #     attempt_limit: 3
      #     attempt_delay: 15000
      #     with: |
      #       image: ${{ env.BUILDER_IMAGE }}
      #       tags: ${{ steps.generate-tags.outputs.tags }}
      #       registry: ${{ env.IMAGE_REGISTRY }}
      #       username: ${{ env.REGISTRY_USER }}
      #       password: ${{ env.REGISTRY_PASSWORD }}
      #       extra-args: |
      #         --disable-content-trust

      - name: Separate debuginfo into different folder
        run: |
          cd kernel
          mkdir -p debuginfo
          mv ${{ matrix.arch }}/kernel-debuginfo-*.rpm debuginfo/

      - name: Upload Kernel to action
        uses: actions/upload-artifact@v4
        with:
          name: kernel-f${{ matrix.fedora_version}}-${{ matrix.arch }}
          path: |
            .build-*.log
            kernel/${{ matrix.arch }}/kernel-*.rpm
          compression-level: 7

      - name: Upload Kernel debuginfo to action
        uses: actions/upload-artifact@v4
        with:
          name: kernel-f${{ matrix.fedora_version}}-${{ matrix.arch }}-debuginfo
          path: |
            .build-*.log
            kernel/debuginfo/*.rpm
          compression-level: 7
      
      - name: Upload Kernel to release
        if: github.event_name == 'release'
        uses: Wandalen/wretry.action@v3.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          attempt_limit: 3
          attempt_delay: 15000
          action: softprops/action-gh-release@v2
          with: |
            files: |
              kernel/${{ matrix.arch }}/kernel-*.rpm
              kernel/x86_64/linux-*.pkg.tar.zst
              kernel/x86_64/linux-*.pkg.tar.zst.sig
            fail_on_unmatched_files: false
            make_latest: false

      # We always want to save the newest ccache
      - name: Backup ccache
        # Don't use cache on releases as github does not allow it
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/cache/save@v4
        with:
          path: ccache
          key: ccache-${{ matrix.arch }}-${{ github.sha }}

  # Trigger ublue-os/akmods build/kernel cache
  # post_release:
  #   runs-on: ubuntu-24.04
  #   needs: build_kernel
  #   if: github.event_name == 'release'
  #   steps:
  #     - name: Make release latest
  #       if: github.event.release.prerelease == false
  #       uses: Wandalen/wretry.action@v3.8.0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         attempt_limit: 3
  #         attempt_delay: 15000
  #         action: softprops/action-gh-release@v2
  #         with: |
  #           make_latest: true

  #     - name: Trigger Kernel Cache
  #       run: |
  #         repo_owner="ublue-os"
  #         repo_name="akmods"
  #         event_type="bazzite-kernel-build"
  #         release_tag="${{ github.event.release.tag_name }}"

  #         curl -L \
  #           -X POST \
  #           -H "Accept: application/vnd.github+json" \
  #           -H "Authorization: Bearer ${{ secrets.UBLUE_PAT }}" \
  #           -H "X-GitHub-Api-Version: 2022-11-28" \
  #           https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
  #           -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"release_tag\": \"$release_tag\"}}"
  # update_aur:
  #   uses: ./.github/workflows/publish-aur.yml
  #   needs: build_kernel
  #   secrets: inherit
  #   if: github.event_name == 'release' && github.event.release.prerelease == false
  #   with:
  #     relver: ${{ github.event.release.tag_name }}
  #     fedora_version: 41 #arch_fedora
